baseURL = 'https://pevenc12.github.io/'
languageCode = 'zh-tw'
title = 'blog.p'
theme="archie"
copyright = "© Peven"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	useCDN=false
	subtitle = "人生目標是在死之前努力學習。"


paginate=3

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/PevenC"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/po-chih-chang-2b9847113/"


[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/peven.chang"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3